package com.karwisoft.learnspace.beans;// default package
// Generated 25 juin 2018 11:15:45 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Messages generated by hbm2java
 */
@Entity
@Table(name = "messages", catalog = "quranspace")
public class Messages implements java.io.Serializable {

	private Integer idMsg;
	private String message;
	private String Expediteur;
	private String Destinataire;
	private String date;
	private String type;

	public Messages() {
	}

	public Messages(String message, String Expediteur, String Destinataire, String date, String type) {
		this.message = message;
		this.Expediteur = Expediteur;
		this.Destinataire = Destinataire;
		this.date = date;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_msg", unique = true, nullable = false)
	public Integer getIdMsg() {
		return this.idMsg;
	}

	public void setIdMsg(Integer idMsg) {
		this.idMsg = idMsg;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "expediteur", nullable = false, length = 155)
	public String getExpediteur() {
		return this.Expediteur;
	}

	public void setExpediteur(String Expediteur) {
		this.Expediteur = Expediteur;
	}

	@Column(name = "destinataire", nullable = false, length = 155)
	public String getDestinataire() {
		return this.Destinataire;
	}

	public void setDestinataire(String Destinataire) {
		this.Destinataire = Destinataire;
	}

	@Column(name = "date", nullable = false, length = 10)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "type", nullable = false, length = 55)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}
}
