package com.karwisoft.learnspace.beans;

// default package
// Generated 27 avr. 2018 13:23:37 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "review", catalog = "quranspace")
public class Review implements java.io.Serializable {

	private Integer idReview;
	private int note;
	private String subject;
	private String description;
	private int idTutor;
	private int idStudent;

	public Review() {
	}

	public Review(String subject, String description, int idTutor, int idStudent, int note) {
		this.subject = subject;
		this.description = description;
		this.idTutor = idTutor;
		this.idStudent = idStudent;
		this.note = note;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_review", unique = true, nullable = false)
	public Integer getIdReview() {
		return this.idReview;
	}

	public void setIdReview(Integer idReview) {
		this.idReview = idReview;
	}


	@Column(name = "note", nullable = false)
	public int getNote() {
		return this.note;
	}

	public void setNote(int note) {
		this.note = note;
	}
	
	@Column(name = "subject", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "description", nullable = false, length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "id_tutor", nullable = false)
	public int getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(int idTutor) {
		this.idTutor = idTutor;
	}

	@Column(name = "id_student", nullable = false)
	public int getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

}
