package com.karwisoft.learnspace.beans;

// default packbirthdate
// Generated 27 avr. 2018 13:23:37 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "quranspace")
public class Student implements java.io.Serializable {

	private Integer idStudent;
	private String name;
	private String picture;
	private String aboutMe;
	private String subjects;
	private String birthdate;
	private String gender;
	private String spokenlanguage;
	private String riwayaToLearn;
	private String certifications;
	private String learningPreferences;
	private String communication;
	private String location;
	private String timeZone;
	private String membershipStartDate;
	private String reviews;
	private String email;
	private String password;
	private Integer actif;

	public Student() {
	}

	public Student(String name, String picture, String aboutMe, String subjects, String birthdate, String gender, 
			String spokenlanguage, String riwayaToLearn, String certifications, String learningPreferences, String communication,
			String location, String timeZone, String membershipStartDate, String reviews, String email, String password, Integer actif) {
		this.name = name;
		this.picture = picture;
		this.aboutMe = aboutMe;
		this.subjects = subjects;
		this.birthdate = birthdate;
		this.gender = gender;
		this.spokenlanguage = spokenlanguage;
		this.riwayaToLearn = riwayaToLearn;
		this.certifications = certifications;
		this.learningPreferences = learningPreferences;
		this.communication = communication;
		this.location = location;
		this.timeZone = timeZone;
		this.membershipStartDate = membershipStartDate;
		this.reviews = reviews;
		this.email = email;
		this.password = password;
		this.actif = actif;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_student", unique = true, nullable = false)
	public Integer getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(Integer idStudent) {
		this.idStudent = idStudent;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture", nullable = false)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "about_me", length = 65535)
	public String getAboutMe() {
		return this.aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	@Column(name = "subjects", nullable = false, length = 255)
	public String getsubjects() {
		return this.subjects;
	}

	public void setsubjects(String subjects) {
		this.subjects = subjects;
	}

	@Column(name = "birth_date")
	public String getbirthdate() {
		return this.birthdate;
	}

	public void setbirthdate(String birthdate) {
		this.birthdate = birthdate;
	}

	@Column(name = "gender", nullable = false, length = 15)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "spoken_language", length = 50)
	public String getSpokenlanguage() {
		return this.spokenlanguage;
	}

	public void setSpokenlanguage(String spokenlanguage) {
		this.spokenlanguage = spokenlanguage;
	}
	
	@Column(name = "riwaya_to_learn", length = 65535)
	public String getRiwayaToLearn() {
		return this.riwayaToLearn;
	}

	public void setRiwayaToLearn(String riwayaToLearn) {
		this.riwayaToLearn = riwayaToLearn;
	}

	@Column(name = "certifications", length = 65535)
	public String getCertifications() {
		return this.certifications;
	}

	public void setCertifications(String certifications) {
		this.certifications = certifications;
	}

	@Column(name = "learning_preferences", length = 65535)
	public String getLearningPreferences() {
		return this.learningPreferences;
	}

	public void setLearningPreferences(String learningPreferences) {
		this.learningPreferences = learningPreferences;
	}
	
	@Column(name = "communication", length = 55)
	public String getCommunication() {
		return this.communication;
	}

	public void setCommunication(String communication) {
		this.communication = communication;
	}

	@Column(name = "location", length = 60)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "time_zone", nullable = false, length = 60)
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "membership_start_date", nullable = false)
	public String getMembershipStartDate() {
		return this.membershipStartDate;
	}

	public void setMembershipStartDate(String membershipStartDate) {
		this.membershipStartDate = membershipStartDate;
	}


	@Column(name = "reviews", length = 65535)
	public String getReviews() {
		return this.reviews;
	}

	public void setReviews(String reviews) {
		this.reviews = reviews;
	}
	
	@Column(name = "email", nullable = false, length = 255)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	@Column(name = "actif")
	public Integer getActif() {
		return this.actif;
	}

	public void setActif(Integer actif) {
		this.actif = actif;
	}
}
