// default package
// Generated 25 juin 2018 11:15:45 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Calendar generated by hbm2java
 */
@Entity
@Table(name = "calendar", catalog = "quranspace")
public class Calendar implements java.io.Serializable {

	private Integer idCalendar;
	private String date;
	private String heure;
	private int idClasses;
	private int idTutor;

	public Calendar() {
	}

	public Calendar(String date, String heure, int idClasses, int idTutor) {
		this.date = date;
		this.heure = heure;
		this.idClasses = idClasses;
		this.idTutor = idTutor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_calendar", unique = true, nullable = false)
	public Integer getIdCalendar() {
		return this.idCalendar;
	}

	public void setIdCalendar(Integer idCalendar) {
		this.idCalendar = idCalendar;
	}

	@Column(name = "date", nullable = false, length = 15)
	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	@Column(name = "heure", nullable = false, length = 15)
	public String getHeure() {
		return this.heure;
	}

	public void setHeure(String heure) {
		this.heure = heure;
	}

	@Column(name = "id_classes", nullable = false)
	public int getIdClasses() {
		return this.idClasses;
	}

	public void setIdClasses(int idClasses) {
		this.idClasses = idClasses;
	}

	@Column(name = "id_tutor", nullable = false)
	public int getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(int idTutor) {
		this.idTutor = idTutor;
	}

}
