// default package
// Generated 7 mai 2018 10:19:17 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MediaTutor generated by hbm2java
 */
@Entity
@Table(name = "media_tutor", catalog = "quranspace")
public class MediaTutor implements java.io.Serializable {

	private Integer idMediaTutor;
	private String idMedia;
	private String idTutor;

	public MediaTutor() {
	}

	public MediaTutor(String idMedia, String idTutor) {
		this.idMedia = idMedia;
		this.idTutor = idTutor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_media_tutor", unique = true, nullable = false)
	public Integer getIdMediaTutor() {
		return this.idMediaTutor;
	}

	public void setIdMediaTutor(Integer idMediaTutor) {
		this.idMediaTutor = idMediaTutor;
	}

	@Column(name = "id_media", nullable = false, length = 11)
	public String getIdMedia() {
		return this.idMedia;
	}

	public void setIdMedia(String idMedia) {
		this.idMedia = idMedia;
	}

	@Column(name = "id_tutor", nullable = false, length = 11)
	public String getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(String idTutor) {
		this.idTutor = idTutor;
	}

}
