// default package
// Generated 7 mai 2018 10:19:17 by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MediaStudent generated by hbm2java
 */
@Entity
@Table(name = "media_student", catalog = "quranspace")
public class MediaStudent implements java.io.Serializable {

	private MediaStudentId id;

	public MediaStudent() {
	}

	public MediaStudent(MediaStudentId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idMediaStudent", column = @Column(name = "id_media_student", nullable = false)),
			@AttributeOverride(name = "idMedia", column = @Column(name = "id_media", nullable = false)),
			@AttributeOverride(name = "idStudent", column = @Column(name = "id_student", nullable = false)) })
	public MediaStudentId getId() {
		return this.id;
	}

	public void setId(MediaStudentId id) {
		this.id = id;
	}

}
