// default package
// Generated 25 juin 2018 11:15:45 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ReviewStudent generated by hbm2java
 */
@Entity
@Table(name = "review_student", catalog = "quranspace")
public class ReviewStudent implements java.io.Serializable {

	private Integer idReviewStudent;
	private int idReview;
	private int idStudent;

	public ReviewStudent() {
	}

	public ReviewStudent(int idReview, int idStudent) {
		this.idReview = idReview;
		this.idStudent = idStudent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_review_student", unique = true, nullable = false)
	public Integer getIdReviewStudent() {
		return this.idReviewStudent;
	}

	public void setIdReviewStudent(Integer idReviewStudent) {
		this.idReviewStudent = idReviewStudent;
	}

	@Column(name = "id_review", nullable = false)
	public int getIdReview() {
		return this.idReview;
	}

	public void setIdReview(int idReview) {
		this.idReview = idReview;
	}

	@Column(name = "id_student", nullable = false)
	public int getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(int idStudent) {
		this.idStudent = idStudent;
	}

}
