// default package
// Generated 7 mai 2018 10:19:17 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "quranspace")
public class Student implements java.io.Serializable {

	private Integer idStudent;
	private String name;
	private String picture;
	private String hourlyRate;
	private String aboutMe;
	private String subjectsIWantLearn;
	private int age;
	private String gender;
	private String riwayaToLearn;
	private String certifications;
	private String learningPreferences;
	private String location;
	private String timeZone;
	private String membershipStartDate;

	public Student() {
	}

	public Student(String name, String picture, String hourlyRate, String aboutMe, String subjectsIWantLearn, int age,
			String gender, String riwayaToLearn, String certifications, String learningPreferences, String location,
			String timeZone, String membershipStartDate) {
		this.name = name;
		this.picture = picture;
		this.hourlyRate = hourlyRate;
		this.aboutMe = aboutMe;
		this.subjectsIWantLearn = subjectsIWantLearn;
		this.age = age;
		this.gender = gender;
		this.riwayaToLearn = riwayaToLearn;
		this.certifications = certifications;
		this.learningPreferences = learningPreferences;
		this.location = location;
		this.timeZone = timeZone;
		this.membershipStartDate = membershipStartDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_student", unique = true, nullable = false)
	public Integer getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(Integer idStudent) {
		this.idStudent = idStudent;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture", nullable = false)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "hourly_rate", nullable = false, length = 60)
	public String getHourlyRate() {
		return this.hourlyRate;
	}

	public void setHourlyRate(String hourlyRate) {
		this.hourlyRate = hourlyRate;
	}

	@Column(name = "about_me", nullable = false, length = 65535)
	public String getAboutMe() {
		return this.aboutMe;
	}

	public void setAboutMe(String aboutMe) {
		this.aboutMe = aboutMe;
	}

	@Column(name = "subjects_i_want_learn", nullable = false, length = 65535)
	public String getSubjectsIWantLearn() {
		return this.subjectsIWantLearn;
	}

	public void setSubjectsIWantLearn(String subjectsIWantLearn) {
		this.subjectsIWantLearn = subjectsIWantLearn;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "gender", nullable = false, length = 15)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "riwaya_to_learn", nullable = false, length = 65535)
	public String getRiwayaToLearn() {
		return this.riwayaToLearn;
	}

	public void setRiwayaToLearn(String riwayaToLearn) {
		this.riwayaToLearn = riwayaToLearn;
	}

	@Column(name = "certifications", nullable = false, length = 65535)
	public String getCertifications() {
		return this.certifications;
	}

	public void setCertifications(String certifications) {
		this.certifications = certifications;
	}

	@Column(name = "learning_preferences", nullable = false, length = 65535)
	public String getLearningPreferences() {
		return this.learningPreferences;
	}

	public void setLearningPreferences(String learningPreferences) {
		this.learningPreferences = learningPreferences;
	}

	@Column(name = "location", nullable = false, length = 60)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "time_zone", nullable = false, length = 60)
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "membership_start_date", nullable = false)
	public String getMembershipStartDate() {
		return this.membershipStartDate;
	}

	public void setMembershipStartDate(String membershipStartDate) {
		this.membershipStartDate = membershipStartDate;
	}

}
