// default package
// Generated 7 mai 2018 10:19:17 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TutLanguage generated by hbm2java
 */
@Entity
@Table(name = "tut_language", catalog = "quranspace")
public class TutLanguage implements java.io.Serializable {

	private Integer idTutLanguage;
	private int idTutor;
	private int idLanguage;

	public TutLanguage() {
	}

	public TutLanguage(int idTutor, int idLanguage) {
		this.idTutor = idTutor;
		this.idLanguage = idLanguage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tut_language", unique = true, nullable = false)
	public Integer getIdTutLanguage() {
		return this.idTutLanguage;
	}

	public void setIdTutLanguage(Integer idTutLanguage) {
		this.idTutLanguage = idTutLanguage;
	}

	@Column(name = "id_tutor", nullable = false)
	public int getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(int idTutor) {
		this.idTutor = idTutor;
	}

	@Column(name = "id_language", nullable = false)
	public int getIdLanguage() {
		return this.idLanguage;
	}

	public void setIdLanguage(int idLanguage) {
		this.idLanguage = idLanguage;
	}

}
