// default package
// Generated 25 juin 2018 11:15:45 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tuto generated by hbm2java
 */
@Entity
@Table(name = "tuto", catalog = "quranspace")
public class Tuto implements java.io.Serializable {

	private Integer idTutor;
	private String name;
	private String picture;
	private String hourly;
	private String email;
	private String password;
	private int nbReviews;
	private String about;
	private String subjectIcanteach;
	private int age;
	private String gender;
	private String riwaya;
	private String subjectVerif;
	private String certification;
	private String recitation;
	private String teachPreference;
	private String mediaCam;
	private String location;
	private String language;
	private String previewExperience;
	private int actif;
	private String timeZone;
	private String membershipStartDate;

	public Tuto() {
	}

	public Tuto(String name, String picture, String hourly, String email, String password, int nbReviews, String about,
			String subjectIcanteach, int age, String gender, String riwaya, String subjectVerif, String certification,
			String recitation, String teachPreference, String mediaCam, String location, String language,
			String previewExperience, int actif, String timeZone, String membershipStartDate) {
		this.name = name;
		this.picture = picture;
		this.hourly = hourly;
		this.email = email;
		this.password = password;
		this.nbReviews = nbReviews;
		this.about = about;
		this.subjectIcanteach = subjectIcanteach;
		this.age = age;
		this.gender = gender;
		this.riwaya = riwaya;
		this.subjectVerif = subjectVerif;
		this.certification = certification;
		this.recitation = recitation;
		this.teachPreference = teachPreference;
		this.mediaCam = mediaCam;
		this.location = location;
		this.language = language;
		this.previewExperience = previewExperience;
		this.actif = actif;
		this.timeZone = timeZone;
		this.membershipStartDate = membershipStartDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tutor", unique = true, nullable = false)
	public Integer getIdTutor() {
		return this.idTutor;
	}

	public void setIdTutor(Integer idTutor) {
		this.idTutor = idTutor;
	}

	@Column(name = "name", nullable = false, length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "picture", nullable = false)
	public String getPicture() {
		return this.picture;
	}

	public void setPicture(String picture) {
		this.picture = picture;
	}

	@Column(name = "hourly", nullable = false, length = 60)
	public String getHourly() {
		return this.hourly;
	}

	public void setHourly(String hourly) {
		this.hourly = hourly;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nb_reviews", nullable = false)
	public int getNbReviews() {
		return this.nbReviews;
	}

	public void setNbReviews(int nbReviews) {
		this.nbReviews = nbReviews;
	}

	@Column(name = "about", nullable = false, length = 65535)
	public String getAbout() {
		return this.about;
	}

	public void setAbout(String about) {
		this.about = about;
	}

	@Column(name = "subject_icanteach", nullable = false, length = 65535)
	public String getSubjectIcanteach() {
		return this.subjectIcanteach;
	}

	public void setSubjectIcanteach(String subjectIcanteach) {
		this.subjectIcanteach = subjectIcanteach;
	}

	@Column(name = "age", nullable = false)
	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	@Column(name = "gender", nullable = false, length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "riwaya", nullable = false, length = 65535)
	public String getRiwaya() {
		return this.riwaya;
	}

	public void setRiwaya(String riwaya) {
		this.riwaya = riwaya;
	}

	@Column(name = "subject_verif", nullable = false, length = 65535)
	public String getSubjectVerif() {
		return this.subjectVerif;
	}

	public void setSubjectVerif(String subjectVerif) {
		this.subjectVerif = subjectVerif;
	}

	@Column(name = "certification", nullable = false, length = 65535)
	public String getCertification() {
		return this.certification;
	}

	public void setCertification(String certification) {
		this.certification = certification;
	}

	@Column(name = "recitation", nullable = false)
	public String getRecitation() {
		return this.recitation;
	}

	public void setRecitation(String recitation) {
		this.recitation = recitation;
	}

	@Column(name = "teach_preference", nullable = false, length = 65535)
	public String getTeachPreference() {
		return this.teachPreference;
	}

	public void setTeachPreference(String teachPreference) {
		this.teachPreference = teachPreference;
	}

	@Column(name = "media_cam", nullable = false, length = 65535)
	public String getMediaCam() {
		return this.mediaCam;
	}

	public void setMediaCam(String mediaCam) {
		this.mediaCam = mediaCam;
	}

	@Column(name = "location", nullable = false)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "language", nullable = false, length = 55)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "preview_experience", nullable = false, length = 65535)
	public String getPreviewExperience() {
		return this.previewExperience;
	}

	public void setPreviewExperience(String previewExperience) {
		this.previewExperience = previewExperience;
	}

	@Column(name = "actif", nullable = false)
	public int getActif() {
		return this.actif;
	}

	public void setActif(int actif) {
		this.actif = actif;
	}

	@Column(name = "time_zone", nullable = false, length = 155)
	public String getTimeZone() {
		return this.timeZone;
	}

	public void setTimeZone(String timeZone) {
		this.timeZone = timeZone;
	}

	@Column(name = "membership_start_date", nullable = false, length = 12)
	public String getMembershipStartDate() {
		return this.membershipStartDate;
	}

	public void setMembershipStartDate(String membershipStartDate) {
		this.membershipStartDate = membershipStartDate;
	}

}
